[project]
name = "vectorless-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.136.1",
    "langgraph>=1.1.10",
    "openai>=2.33.0",
    "openai-agents>=0.14.8",
    "pydantic>=2.13.3",
    "pymupdf>=1.27.2.3",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.27",
    "supabase>=2.29.0",
    "uvicorn>=0.46.0",
]
